[[plugins]]
repo = 'Shougo/neocomplete.vim'
disabled = '!has("lua")'
on_i = 1

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

[[plugins]]
repo = 'rhysd/vim-textobj-ruby'
depends = 'vim-textobj-user'
on_ft = 'ruby'
