# Changes here will be overwritten by Copier
_commit: v0.3.10
_src_path: https://github.com/fohte/generic-boilerplate
description: ''
is_public: false
project_name: dotfiles
subpackages: []
type: base
use_release_please: false
