#!/bin/bash

if match_tag bin; then
  sym bin ~/bin
fi

if match_tag fzf; then
  sym "$(brew --prefix)/opt/fzf" ~/.fzf
fi

if match_tag git; then
  sym config/git ~/.config/git
fi

if match_tag tig; then
  sym config/tig/.tigrc ~/.tigrc
fi

if match_tag nvim; then
  sym config/nvim ~/.config/nvim
fi

if match_tag editorconfig; then
  sym config/editorconfig/.editorconfig ~/.editorconfig
fi

if match_tag efm; then
  sym config/efm-langserver ~/.config/efm-langserver
fi

if match_tag zsh; then
  sym config/zsh/.zshrc ~/.zshrc
  sym config/zsh/.zshenv ~/.zshenv
  sym config/zsh/rc ~/.config/zsh/rc
  sym config/zsh/env ~/.config/zsh/env
fi

if match_tag tmux; then
  sym roles/tmux/files/.tmux.conf ~/.tmux.conf
  sym roles/tmux/files/.tmux.macos.conf ~/.tmux.macos.conf
fi

if match_tag wezterm; then
  sym config/wezterm ~/.config/wezterm
fi

if match_tag hammerspoon; then
  sym config/hammerspoon/init.lua ~/.hammerspoon/init.lua
fi

if match_tag rg; then
  sym config/rg/.rgignore ~/.rgignore
fi

if match_tag karabiner && is_macos; then
  sym config/karabiner/assets/complex_modifications \
    ~/.config/karabiner/assets/complex_modifications
fi

if match_tag espanso; then
  # these paths can be referenced from `espanso path config`
  # See: https://espanso.org/docs/configuration/basics/
  is_linux && espanso_config_path="$HOME/.config/espanso"
  is_macos && espanso_config_path="$HOME/Library/Application Support/espanso"

  sym config/espanso "$espanso_config_path"
fi

if match_tag gpg; then
  sym config/gnupg/gpg-agent.conf ~/.gnupg/gpg-agent.conf
fi

if match_tag prettier; then
  sym roles/node/files/.prettierrc ~/.prettierrc
fi

if match_tag yabai; then
  sym config/yabai/yabairc ~/.config/yabai/yabairc
fi
