- name: Install fcitx and mozc with apt
  become: true
  apt:
    name: fcitx-mozc
    state: latest

- name: Create fcitx config directory
  file:
    path: '{{ user_home }}/.config/fcitx'
    state: directory

- name: Symlink fcitx files
  file:
    src: '{{ dotfiles_home }}/roles/fcitx/files/{{ item }}'
    dest: '{{ user_home }}/.config/fcitx/{{ item }}'
    state: link
  with_items:
    - config
