# yaml-language-server: $schema=https://raw.githubusercontent.com/fohte/runok/main/schema/runok.schema.json

rules:
  - allow: 'go doc *'
    tests:
      - allow: 'go doc fmt'
  - allow: 'go env *'
  - allow: 'go version *'
  - allow: 'go build|test|vet|list *'
  - allow: 'go mod why|graph|verify|download *'
  - allow: 'go tool *'
  - allow: 'gotest *'
  - allow: 'gofmt *'
  - allow: 'goimports *'
  - allow: 'golangci-lint *'
  - allow: 'staticcheck *'
  - allow: 'errcheck *'
