# yaml-language-server: $schema=https://raw.githubusercontent.com/fohte/runok/main/schema/runok.schema.json

definitions:
  wrappers:
    - 'bundle exec <cmd>'

rules:
  - allow: 'bundle show *'
  - allow: 'bundle info *'
  - allow: 'bundle list *'
  - allow: 'bundle env'
  - allow: 'bundle config'
  - allow: 'bundle config get *'
  - allow: 'bundle config list'
  - allow: 'bundle check'
    tests:
      - allow: 'bundle check'
  - allow: 'gem list|which|contents|environment|env *'
    tests:
      - allow: 'gem list grpc -e'
      - allow: 'gem list wantedly -e'
      - allow: 'gem list redis -a'
      - allow: 'gem list -i servicex'
      - allow: "gem list -i rails -v '5.2.5'"
      - allow: 'gem which grpc'
      - allow: 'gem contents retryable'
      - allow: 'gem environment gemdir'
      - allow: 'gem env gempath'
  - allow: 'ruby *'
    sandbox: readonly
  - allow: 'ruby -c *'
    tests:
      - allow: 'ruby -c script.rb'
  - allow: 'bundle install *'
  - allow: 'rspec *'
    tests:
      - allow: 'rspec spec/foo_spec.rb'
      - allow: 'bundle exec rspec spec/foo_spec.rb'
  - allow: 'rubocop *'
    tests:
      - allow: 'rubocop lib'
      - allow: 'bundle exec rubocop lib'
