- name: Install requirements to install pyenv
  become: true
  apt:
    name:
      - build-essential
      - curl
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - llvm
      - make
      - wget
      - zlib1g-dev
    state: present

- name: Clone pyenv
  git:
    repo: https://github.com/yyuu/pyenv.git
    dest: '{{ pyenv_root }}'
  register: git_result
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"
