- include_tasks: macos.yml
  when: is_macos

- include_tasks: debian.yml
  when: is_debian

- name: Install Python with pyenv
  command: zsh -lc 'pyenv install {{ item }}'
  args:
    creates: '{{ pyenv_root }}/versions/{{ item }}'
  with_items: '{{ python.install_versions }}'

- name: Set global Python version
  template:
    src: ../templates/versions.j2
    dest: '{{ pyenv_root }}/version'

- name: Symlink python files
  file:
    src: '{{ dotfiles_home }}/roles/python/files/{{ item }}'
    dest: '{{ user_home }}/{{ item }}'
    state: link
  with_items:
    - .isort.cfg

- name: Install python packages with pip
  pip:
    name: '{{ python.global_packages }}'
    state: latest
    executable: '{{ pyenv_root }}/shims/pip'
