variables:
  repo: gh repo view --json name,visibility,owner --jq .
  has_release_please: 'root=$(git rev-parse --show-toplevel) && [ -f "$root/release-please-config.json" -o -f "$root/.release-please-manifest.json" ] && echo true || echo false'
  repo_language: a config get repo.language

template: template.md
