- name: Install xkeysnail with pip
  pip:
    name: xkeysnail
    state: latest
    executable: '{{ pyenv_root }}/shims/pip'

- name: Create xkeysnail config directory
  file:
    path: '{{ user_home }}/.config/xkeysnail'
    state: directory

- name: Symlink xkeysnail files
  file:
    src: '{{ dotfiles_home }}/roles/xkeysnail/files/{{ item }}'
    dest: '{{ user_home }}/.config/xkeysnail/{{ item }}'
    # use hard link because soft link dosen't work
    state: hard
  with_items:
    - config.py

- name: Create xkeysnail.service
  become: true
  template:
    src: xkeysnail.service.j2
    dest: /etc/systemd/system/xkeysnail.service

- name: Enable and start xkeysnail service
  become: true
  systemd:
    name: xkeysnail.service
    daemon_reload: true
    enabled: true
    state: restarted
