registries:
  - type: standard
    ref: v4.300.1 # renovate: depName=aquaproj/aqua-registry
packages:
  - name: cli/cli@v2.74.0
  - name: sharkdp/bat@v0.25.0
  - name: x-motemen/ghq@v1.7.1
  - name: junegunn/fzf@v0.61.1
  - name: junegunn/fzf/fzf-tmux@v0.61.1
  - name: dandavison/delta@0.18.2
  - name: 1password/cli@v2.30.0
  - name: mikefarah/yq@v4.45.4
  - name: JohnnyMorganz/StyLua@v2.1.0
  - name: mvdan/sh@v3.11.0
  - name: koalaman/shellcheck@v0.10.0
  - name: pre-commit/pre-commit@v4.2.0
  - name: neovim/neovim@v0.11.1
  - name: google/go-jsonnet@v0.20.0
  - name: pkgxdev/pkgx@v2.5.0
  - name: eza-community/eza@v0.21.3
  - name: starship/starship@v1.23.0
  - name: BurntSushi/ripgrep@14.1.1
  - name: jdx/mise@v2025.5.9
