registries:
  - type: standard
    ref: v4.300.1 # renovate: depName=aquaproj/aqua-registry
packages:
  - name: cli/cli@v2.66.1
  - name: nodejs/node@v23.5.0
  - name: sharkdp/bat@v0.25.0
  - name: x-motemen/ghq@v1.7.1
  - name: junegunn/fzf@v0.59.0
  - name: junegunn/fzf/fzf-tmux@v0.59.0
  - name: dandavison/delta@0.18.2
  - name: 1password/cli@v2.30.0
  - name: mikefarah/yq@v4.45.1
  - name: JohnnyMorganz/StyLua@v0.20.0
  - name: mvdan/sh@v3.10.0
  - name: koalaman/shellcheck@v0.10.0
  - name: pre-commit/pre-commit@v4.1.0
  - name: neovim/neovim@v0.10.4
  - name: google/go-jsonnet@v0.20.0
  - name: pkgxdev/pkgx@v2.1.2
  - name: eza-community/eza@v0.20.20
  - name: starship/starship@v1.22.1
  - name: BurntSushi/ripgrep@14.1.1
