registries:
  - type: standard
    ref: v4.223.0 # renovate: depName=aquaproj/aqua-registry
packages:
  - name: cli/cli@v2.64.0
  - name: nodejs/node@v23.5.0
  - name: sharkdp/bat@v0.24.0
  - name: x-motemen/ghq@v1.6.2
  - name: junegunn/fzf@v0.55.0
  - name: junegunn/fzf/fzf-tmux@v0.55.0
  - name: dandavison/delta@0.18.2
  - name: 1password/cli@v2.30.0
  - name: mikefarah/yq@v4.44.3
  - name: JohnnyMorganz/StyLua@v0.20.0
  - name: mvdan/sh@v3.9.0
  - name: koalaman/shellcheck@v0.10.0
  - name: pre-commit/pre-commit@v4.0.1
  - name: neovim/neovim@v0.10.2
  - name: google/go-jsonnet@v0.20.0
  - name: pkgxdev/pkgx@v1.2.2
  - name: eza-community/eza@v0.20.5
  - name: starship/starship@v1.21.1
  - name: BurntSushi/ripgrep@14.1.1
