registries:
  - type: standard
    ref: v4.219.0 # renovate: depName=aquaproj/aqua-registry
packages:
  - name: cli/cli@v2.55.0
  - name: nodejs/node@v22.7.0
  - name: sharkdp/bat@v0.24.0
  - name: x-motemen/ghq@v1.6.2
  - name: junegunn/fzf@v0.55.0
  - name: junegunn/fzf/fzf-tmux@v0.55.0
  - name: dandavison/delta@0.18.1
  - name: 1password/cli@v2.30.0
  - name: mikefarah/yq@v4.44.3
  - name: JohnnyMorganz/StyLua@v0.20.0
  - name: mvdan/sh@v3.9.0
  - name: koalaman/shellcheck@v0.10.0
  - name: pre-commit/pre-commit@v3.8.0
  - name: neovim/neovim@v0.10.1
