- name: Install kitty with Homebrew Cask
  homebrew_cask:
    name: kitty
    state: latest

- name: Symlink kitty files
  file:
    src: '{{ dotfiles_home }}/roles/kitty/files/{{ item.src }}'
    dest: '{{ user_home }}/Library/Preferences/kitty/{{ item.dest }}'
    state: link
  with_items:
    - src: shared.conf
      dest: kitty.conf
    - src: macos.conf
      dest: os.conf
