- name: Install kitty with Homebrew Cask
  homebrew_cask:
    name: kitty
    state: latest

- name: Symlink kitty files
  file:
    src: '{{ dotfiles_home }}/roles/kitty/files/{{ item }}'
    dest: '{{ user_home }}/Library/Preferences/kitty/{{ item }}'
    state: link
  with_items:
    - kitty.conf
