- name: Install i3 with apt
  become: true
  apt:
    name: i3
    state: latest

- name: Create i3 config directory
  file:
    path: '{{ user_home }}/.config/i3'
    state: directory

- name: Symlink i3 files
  file:
    src: '{{ dotfiles_home }}/roles/i3/files/{{ item }}'
    dest: '{{ user_home }}/.config/i3/{{ item }}'
    state: link
  with_items:
    - config.d
