- name: Install i3 with apt
  become: true
  apt:
    name:
      - autoconf 
      - automake
      - libev-dev 
      - libpango1.0-dev 
      - libstartup-notification0-dev 
      - libxcb-cursor-dev 
      - libxcb-icccm4-dev 
      - libxcb-keysyms1-dev 
      - libxcb-randr0-dev 
      - libxcb-shape0-dev
      - libxcb-util0-dev 
      - libxcb-xinerama0-dev 
      - libxcb-xkb-dev 
      - libxcb-xrm-dev 
      - libxcb-xrm0 
      - libxcb1-dev 
      - libxkbcommon-dev 
      - libxkbcommon-x11-dev 
      - libyajl-dev 

# cd /tmp
#
# # clone the repository
# git clone https://www.github.com/Airblader/i3 i3-gaps
# cd i3-gaps
#
# # compile & install
# autoreconf --force --install
# rm -rf build/
# mkdir -p build && cd build/
#
# # Disabling sanitizers is important for release versions!
# # The prefix and sysconfdir are, obviously, dependent on the distribution.
# ../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers
# make
# sudo make install
    state: latest

- name: Create i3 config directory
  file:
    path: '{{ user_home }}/.config/i3'
    state: directory

- name: Symlink i3 files
  file:
    src: '{{ dotfiles_home }}/roles/i3/files/{{ item }}'
    dest: '{{ user_home }}/.config/i3/{{ item }}'
    state: link
  with_items:
    - config
