- include_tasks: macos.yml
  when: is_macos

- include_tasks: debian.yml
  when: is_debian

- name: Install fzf binary, key bindings and completion
  command: '{{ fzf_root }}/install --key-bindings --completion --no-update-rc'
  args:
    creates: '{{ fzf_root }}/bin/fzf'
