# yaml-language-server: $schema=https://raw.githubusercontent.com/fohte/runok/main/schema/runok.schema.json

rules:
  - allow: docker inspect *
  - allow: docker compose up *
  - allow: docker compose logs *
  - allow: docker logs *
