# yaml-language-server: $schema=https://raw.githubusercontent.com/fohte/runok/main/schema/runok.schema.json

rules:
  - allow: 'kubectl get|describe|logs *'
  - ask: 'kubectl get secrets *'

  - allow: 'helm get|show|list *'
