#!/usr/bin/env bash

# global settings
yabai -m config \
  mouse_follows_focus off \
  focus_follows_mouse autofocus \
  mouse_modifier fn

# space settings
yabai -m config \
  layout layout \
  top_padding 0 \
  bottom_padding 0 \
  left_padding 0 \
  right_padding 0 \
  window_gap 0 \
  auto_balance off
