#!/usr/bin/env bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config \
  mouse_follows_focus on \
  focus_follows_mouse autoraise \
  mouse_modifier fn

padding=10

# layout settings
yabai -m config \
  layout bsp \
  top_padding "$padding" \
  bottom_padding "$padding" \
  left_padding "$padding" \
  right_padding "$padding" \
  window_gap "$padding" \
  auto_balance off

yabai -m rule --add app='^System Settings$' manage='off'
