#!/usr/bin/env bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config \
  mouse_follows_focus on \
  focus_follows_mouse autoraise \
  mouse_modifier fn

padding=10

# layout settings
yabai -m config \
  layout bsp \
  top_padding "$padding" \
  bottom_padding "$padding" \
  left_padding "$padding" \
  right_padding "$padding" \
  window_gap "$padding" \
  auto_balance off

manage_off() {
  yabai -m rule --add manage=off mouse_follows_focus=off app="$1"
}

manage_off subrole="^AXSystemDialog$"       # alert, dialog, etc.
manage_off app='^Ivory$' title='- Compose$' # posting window

# Preferences for some apps
manage_off app='^System Settings$'
manage_off app='^ChatGPT$' title='^Settings$'
manage_off app='^Arc$' title='^Fohte$' # Settings' title is set to the user's name

# workaround for Picture in Picture not starting when switching tabs in Arc browser
# ref: https://github.com/koekeishiya/yabai/issues/1669
manage_off title="^Picture in Picture$"

manage_off app='^Notes$' title='^(?!Notes$).*' # Quick note
