format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
${custom.aws_sso_valid}\
${custom.aws_sso_expired}\
$time\
$cmd_duration\
$line_break\
$character"""

[time]
disabled = false
time_format = "%H:%M:%S"
format = '[$time]($style) '
style = "bright-black"

[directory]
style = "blue"
truncate_to_repo = false
truncation_length = 0

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❯](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style) "
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[custom.aws_sso_valid]
command = "check-aws-sso-status && echo '󰅠'" # nf-md-cloud_check
when = "command -v check-aws-sso-status"
shell = "bash"
format = "[$output]($style) "
style = "bright-green"

[custom.aws_sso_expired]
command = "check-aws-sso-status; [ $? -eq 1 ] && echo '󰧠'" # nf-md-cloud_alert
when = "command -v check-aws-sso-status"
shell = "bash"
format = "[$output]($style) "
style = "bright-red"
