- name: Install rofi with apt
  become: true
  apt:
    name: rofi
    state: latest

- name: Create rofi config directory
  file:
    path: '{{ user_home }}/.config/rofi'
    state: directory

- name: Symlink rofi files
  file:
    src: '{{ dotfiles_home }}/roles/rofi/files/{{ item }}'
    dest: '{{ user_home }}/.config/rofi/{{ item }}'
    state: link
  with_items:
    - config
