- name: Install Node.js and npm with apt
  become: true
  apt:
    name:
      - nodejs
      - npm
    state: latest

- name: Symlink .npmrc
  file:
    src: '{{ dotfiles_home }}/roles/node/files/debian/.npmrc'
    dest: '{{ user_home }}/.npmrc'
    state: link
