- name: Install dependencies for Docker
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    state: present

- name: Add Docker apt key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key

- name: Add Docker repository
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable'
    state: present
    update_cache: true

- name: Install Docker with apt
  become: true
  apt:
    name: docker-ce
    state: latest

- name: Enable and start docker service
  systemd:
    name: docker.service
    enabled: true
    state: started
