- include_tasks: macos.yml
  when: is_macos

- include_tasks: debian.yml
  when: is_debian

- name: Symlink .vim
  file:
    src: '{{ dotfiles_home }}/roles/vim/files'
    dest: '{{ user_home }}/.vim'
    state: link

- name: Symlink .vimrc to init.vim
  file:
    src: '{{ dotfiles_home }}/roles/vim/files/init.vim'
    dest: '{{ user_home }}/.vimrc'
    state: link

- name: Symlink ~/.config/nvim
  file:
    src: '{{ dotfiles_home }}/roles/vim/files'
    dest: '{{ user_home }}/.config/nvim'
    state: link

- name: Install vim plugins
  command: nvim +'call dein#install()' +qall
  when: vim.install_plugins

- name: Install Python Neovim client with pip
  pip:
    name: neovim
    state: latest
    executable: '{{ pyenv_root }}/shims/pip'
