- name: Add alacritty repository
  become: true
  apt_repository:
    repo: ppa:mmstick76/alacritty
    state: present

- name: Installe Alacritty with apt
  become: true
  apt:
    name: alacritty
    state: latest

- name: Create a directory for the alacritty config
  file:
    path: '{{ user_home }}/.config/alacritty'
    state: directory

- name: Symlink alacritty files
  file:
    src: '{{ dotfiles_home }}/roles/alacritty/files/{{ item.src }}'
    dest: '{{ user_home }}/.config/alacritty/{{ item.dest }}'
    state: link
  with_items:
    - src: debian.yml
      dest: alacritty.yml
