- name: Symlink alacritty files
  file:
    src: '{{ dotfiles_home }}/roles/alacritty/files/{{ item.src }}'
    dest: '{{ user_home }}/.config/alacritty/{{ item.dest }}'
    state: link
  with_items:
    - src: macos.yml
      dest: alacritty.yml
