# TODO: install latex environment for macOS

- include_tasks: debian.yml
  when: is_debian

- name: Symlink latex files
  file:
    src: '{{ dotfiles_home }}/roles/latex/files/{{ item }}'
    dest: '{{ user_home }}/{{ item }}'
    state: link
  with_items:
    - .latexmkrc
