[tools]
node = "23.11.1"
"npm:@devcontainers/cli" = "0.77.0"

github-cli = "2.74.2"
bat = "0.25.0"
ghq = "1.7.1"
fzf = "0.61.1"
delta = "0.18.2"
yq = "4.45.4"
neovim = "0.11.2"
eza = "0.21.3"
starship = "1.23.0"
ripgrep = "14.1.1"
op = "2.30.0"
difftastic = "0.63.0"
uv = "0.7.16"

[settings]
# disable the idiomatic version file such as Gemfile
# this is the default behavior from the 2025.10.0 version
idiomatic_version_file_enable_tools = []
