- name: Install requirements to install Ruby
  become: true
  apt:
    name:
      - autoconf
      - bison
      - build-essential
      - libffi-dev
      - libgdbm-dev
      - libgdbm5
      - libncurses5-dev
      - libreadline6-dev
      - libssl-dev
      - libyaml-dev
      - zlib1g-dev
    state: present

- name: Clone rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: '{{ rbenv_root }}'
  register: git_result
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"

- name: Clone ruby-build
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: '{{ rbenv_root }}/plugins/ruby-build'
  register: git_result
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"
