name: CI

on:
  push:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Cache aqua packages
        uses: actions/cache@v4
        with:
          path: ~/.local/share/aquaproj-aqua
          key: ${{ runner.os }}-aqua-${{ hashFiles('aqua.yaml') }}
          restore-keys: |
            ${{ runner.os }}-aqua-

      - uses: aquaproj/aqua-installer@v3.1.2
        with:
          aqua_version: v2.43.2
          aqua_opts: '--all' # install all packages immediately to populate cache

      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-

      - name: Run pre-commit hooks
        id: pre-commit
        continue-on-error: true
        run: pre-commit run --all-files

      - name: Commit formatted files
        uses: suzuki-shunsuke/commit-action@v0.0.7
        with:
          commit_message: 'style: auto-format'
          workflow: deny
          github_token: ${{ steps.app-token.outputs.token }}

      - name: Fail if pre-commit failed
        if: steps.pre-commit.outcome == 'failure'
        run: exit 1
