# yaml-language-server: $schema=https://raw.githubusercontent.com/fohte/runok/main/schema/runok.schema.json

rules:
  - allow: 'defaults read *'
  - allow: 'pmset -g *'
  - allow: 'log show *'
  - allow: 'mdfind *'
